<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\QuestionTitle;
class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         $questions = [
            ['title' => '1.Were there any changes to preexisting anti-trafficking legislation during the reporting period (amendments to laws or penal codes, new laws, presidential decrees, supreme court precedents, etc.)? (Tips: Please check if there were any revisions, amendments to laws or penal codes, new laws, presidential decrees, Special Tribunals/Supreme court precedents)',   'status' => 1],
            ['title' => '2Were law enforcement, military, security, state or municipal employees, or other officials or state institutions involved directly in trafficking? (Tips: Please provide information solely based on government documents cleared for public sharing)', 'status' => 1],
            ['title' => '3.Was official involvement in trafficking crimes part of a national directive or policy, including state sponsored forced labor? (Tips: Please provide information solely based on government documents cleared for public sharing and the answer can only be “YES” when the crime is a result of a national directive or policy, including state sponsored forced labor)',  'status' => 1],
            ['title' => '4.Were law enforcement, military, security, state or municipal employees, or other officials allegedly facilitating the crime or obstructing justice (e.g., taking bribes)? (Tips: Please provide information solely based on government documents cleared for public sharing and the answer can only be “YES” when the crime is a result of a national directive or policy, including state sponsored forced labor)',    'status' => 1],
            ['title' => '5.Did the government investigate, prosecute, convict, or sentence any allegedly complicit officials? (Tips: Please provide information solely based on government documents cleared for public sharing and the answer can only be “YES” when the crime is a result of a national directive or policy, including state sponsored forced labor)',    'status' => 1],
            ['title' => '6.Describe government units/courts responsible for investigating, prosecuting, or hearing trafficking cases, such as police units, prosecution offices, labor inspectorate units, and courts: (Tips: For this question, please provide text inputs on the following agencies and their roles in investigating, prosecuting, or hearing trafficking cases)',    'status' => 1],
            ['title' => '7.Were any of these units and their staff exclusively dedicated to trafficking, or was trafficking among various responsibilities/mandates? (Tips: Please note that units such as SPP and SPP are fully dedicated to trafficking cases while other units are having mandate of addressing trafficking cases along with other responsibilities – this can lead to “YES” and “Other”',    'status' => 1],
            ['title' => '8.Did these units/courts have adequate resources? (Tips: Please consider official allocation and review)',    'status' => 1],
            ['title' => '9.Did these units/courts adequately cover all jurisdictions? (Tips: To response, please consider that all the units mentioned are nationwide)',    'status' => 1],
            ['title' => '10.Were there any gaps in law enforcement’s ability to investigate, prosecute, or convict traffickers? Did law enforcement investigate trafficking crimes as other offenses and/or did prosecutors charge alleged traffickers under alternative criminal provisions with lesser penalties (e.g., commercial sex crimes, smuggling of migrants, labor violations, fraud, etc.)? (Tips: For this question, please provide text inputs on known challenges in investigation, prosecution or conviction of traffickers. Along with capacity gaps please consider gaps in accountability)',    'status' => 1],
            ['title' => '11.Does law enforcement pursue trafficking cases that would hold criminally accountable private employers or corporations for forced labor in supply chains? (Tips: For this question, please provide text inputs on investigation based on the national law which holds all actors accountable from private sector to government officials)',    'status' => 1],
            ['title' => '12.Did the government cooperate with foreign counterparts or international law enforcement organizations on any trafficking-related law enforcement activities? (Tips: Please provide text inputs on cooperation with Interpole or any single country or regional body such as SAARC or BIMSTEC- only report the investigations, prosecutions, etc., including extraditions newly carried out in the current reporting period)',    'status' => 1],
            ['title' => '13. Did the government train officials on anti-trafficking enforcement, policies, or laws?  If yes, please describe the number and type of officials trained and the training topics:  If yes, please describe who funded and implemented the training, including any in-kind support from the government: (Tips: Please answer the following two questions in which use official data of your ministry/agency) Did the government train judiciary and court officials on anti-trafficking enforcement, policies, and laws?',    'status' => 1],
            ['title' => '14. Considering what was reported in the 2024 TIP Report country narrative protection section, have there been any new (or changes to preexisting) formal/standard procedures for victim identification? ( Tips: Please mention what changed from previous reporting year by title of the document/tools/ protocol. No need to describe in detail as the following sub questions will capture the detail)',    'status' => 1],
            ['title' => '15.Did front-line officials, including law enforcement, immigration, social services personnel, healthcare workers, and labor inspectors receive adequate training on use of the victim identification protocol or formal written procedures? (Tips: Please consider - Front-line officials of Police, Front-line officials of BGB, Front-line officials of Coastguard , Front-line officials of Ansar, Front-line officials of Immigration, DSS Officials, Labour Inspectors and similar officials of NGO workers, international organization staff, religious officials, and community leaders who come at first contact with VoTs)',    'status' => 1],
            ['title' => '16.Did the victim identification protocol or formal written procedures outline steps to screen members of underserved communities or those at increased risk of trafficking? Such groups could include but are not limited to adults arrested for alleged commercial sex crimes, irregular migrants, asylum seekers, stateless persons, persons with disabilities, unhoused persons, children in welfare systems or aging out of such systems (if applicable, those previously incarcerated, members of marginalized racial and ethnic communities, or individuals or communities living in conflict, crisis, or post-disaster settings). (Tips: Please consider cases related to adults arrested for alleged commercial sex crimes, irregular migrants, asylum seekers, stateless persons, persons with disabilities, unhoused persons, children in welfare systems or aging out of such systems (if applicable, those previously incarcerated, members of marginalized racial and ethnic communities, or individuals or communities living in conflict, crisis, or post-disaster settings)',    'status' => 1],
            ['title' => '17.Did front-line officials, including law enforcement, immigration, social services personnel, healthcare workers, and labor inspectors consistently and systematically use the victim identification protocol or formal written procedures to proactively screen for indicators of human trafficking, including vulnerable and underserved communities? Did the government provide interpreters to conduct interviews in an individual’s primary language? (Tips: Please consider cases related to adults arrested for alleged commercial sex crimes, irregular migrants, asylum seekers, stateless persons, persons with disabilities, unhoused persons, children in welfare systems or aging out of such systems (if applicable, those previously incarcerated, members of marginalized racial and ethnic communities, or individuals or communities living in conflict, crisis, or post-disaster settings)',    'status' => 1],
            ['title' => '18.UKRAINIAN REFUGEES: Since Russia’s further invasion of Ukraine in 2022, have authorities identified any refugees from Ukraine as victims of forced labor or sex trafficking in the country? If so, specify when they were identified and referred to care. Are there ongoing investigations into trafficking of Ukrainian refugees? Please describe government efforts to prevent trafficking among this at-risk population.',    'status' => 1],
            ['title' => '19.VENEZUELAN MIGRANTS: Venezuela’s economic, political, and humanitarian crises have forced millions of people to flee the country. Venezuelan migrants are highly vulnerable to human trafficking. Have authorities identified Venezuelan victims of sex trafficking or forced labor in the country?',    'status' => 1],
            ['title' => '20.Considering what was reported in the 2024 TIP Report country narrative protection section, have there been any new (or changes to preexisting) formal/standard procedures for victim referral to protection services? Did the government have a national referral mechanism or other written procedures to guide officials in referring potential trafficking victims to services? -If yes, please attach a copy of the government’s national referral mechanism or standard procedures for the referral of victims to care upon identification. (Tips: Please review the previous TIP report and read the definition- A National Referral Mechanism (NRM) is a formal framework a government may use to complement victim identification procedures and/or further systematize the identification of trafficking victims to ensure their referral and access to protection services. NRMs should foster intragovernmental coordination (including referrals to law enforcement for action when appropriate); formalize each government entity’s responsibility; and enable communication, collaboration, and partnerships with civil society, IOs, the private sector, and community/religious organizations to ensure victim protection and care. Exact types and uses of NRMs may vary by country and across regions.)',    'status' => 1],
            ['title' => '21.Were front-line officials across government sectors, and all other responsible stakeholders aware of the national referral mechanism and how to use it? (Tips: The definition of the font-line official among others include the following- Front-line officials across government sectors includes law enforcement, immigration, social services personnel, healthcare workers, and labor inspectors and other responsible stakeholders including NGO workers, international organization staff, religious officials, and community leaders. The “other stakeholders” among others include- community people, prospective migrants, vulnerable population such as child labour, displaced population and poor/destitute women. Choose appropriate front-line officials and stakeholders from “choose item” button (the stakeholders’ list is in brown) and provide information)',    'status' => 1],
            ['title' => '22.Did the government systematically and consistently refer identified or potential trafficking victims to social service providers? (Tips: Social service providers can include government services or services delivered by NGOs, international organizations, or religious institutions. “Potential trafficking victims” mean people who are yet to be verified through official guidelines as “identified VoTs”.)',    'status' => 1],
            ['title' => '23.Did the mechanism refer potential or identified victims directly to social service providers or did it require victims to interact with law enforcement first? Were victims required to speak to law enforcement before they were referred to care? Did referral to care take place when victims refused to speak to law enforcement?',    'status' => 1],
            ['title' => '24.Did the government operate any trafficking-specific hotlines or other similar mechanisms, where members of the public could directly reach and receive assistance from first responders? Did the government provide funding to support NGO- operated trafficking-specific hotlines and/or other similar mechanisms? Were these part of the NRM system?',    'status' => 1],
            ['title' => '25.Considering what was reported in the 2024 TIP Report country narrative protection section, have there been any new (or changes to preexisting) procedures or services for victim care? Provide details on the types of services to trafficking victims the government provided or funded. Do not include NGO services delivered unless the government funded the organizations.',    'status' => 1],
            ['title' => '26.Please describe if victim services were general or specialized to trafficking victims’ needs. Indicate if all trafficking survivors could assess the service (including victims of forced labor, foreign victims, adults, and boys) or if only certain groups were eligible. Add any additional details on quality of services, improvements made, or challenges or shortcomings in providing the care.',    'status' => 1],
            ['title' => '27.If there were gaps in victim care (i.e. who may be eligible to access), please describe what the gaps were. Did government policy require a person to be formally identified as a trafficking victim to receive certain services or benefits? If yes, which services or benefits were limited to persons formally identified as trafficking victims? If applicable, which officials were authorized to formally designate individuals as trafficking victims?',    'status' => 1],
            ['title' => '28.Describe the overall quality of care? Did service providers receive adequate training on providing care to trauma survivors? Did service providers have the knowledge and skills to support victims through a consistent victim-centered approach?',    'status' => 1],
            ['title' => '29.How much funding (in the local currency) did the government spend on direct victim care, and assistance (e.g., funds for government shelters, and payments to victims.)',    'status' => 1],
            ['title' => '30.Did the government operate shelters available to trafficking victims? If so, how many government shelters?',    'status' => 1],
            ['title' => '31.Did other stakeholders, including NGOs, IOs, or community/religious based organizations operate shelters available to trafficking victims? If so, how many NGO shelters serving trafficking victims were there?',    'status' => 1],
            ['title' => '32.Were there reports or allegations of misconduct or mistreatment by shelter staff, or unsafe conditions in shelters? If so, what action did the government take?',    'status' => 1],
            ['title' => '33.Were there any populations who lacked access to care, including shelter or other services? (e.g., LGBTQI+ persons, persons with disabilities, men, boys, adults, foreign nationals, etc.) Did all communities receive the same quality and level of access to services?',    'status' => 1],
            ['title' => '34.Were child trafficking victims placed in non-specialized shelters, including homeless shelters, group homes, migrant shelters, or juvenile justice detention centers? What kind of specialized care did they receive in these shelters?',    'status' => 1],
            ['title' => '35.In the case of child trafficking victims, which entity determined whether a child was placed into a shelter, returned to family, or placed in another arrangement such as with a foster family? Did these authorities receive adequate training on trafficking and understand the vulnerabilities of child trauma survivors?',    'status' => 1],
            ['title' => '36.Could adult victims, including persons with disabilities, choose independently to enter a shelter or not, and could they leave shelters unchaperoned when they wanted? Could victims work outside the shelter?',    'status' => 1],
            ['title' => '37.Were foreign victims legally entitled to the same benefits as citizens? Did authorities refer to care foreign trafficking victims? Did foreign victims face any barriers to accessing care?',    'status' => 1],
            ['title' => '38.Were potential trafficking victims incarcerated, fined, or otherwise penalized solely for unlawful acts committed as a direct result of being trafficked (e.g., subject to commercial sex, drug-related, or other criminal charges, or subject to deportation/immigration enforcement or administrative penalties)?',    'status' => 1],
            ['title' => '39.Were members from certain communities, including members of marginalized racial and ethnic communities, more likely to be punished? Were they less likely to be identified as trafficking victims?',    'status' => 1],
            ['title' => '40.Were migrants, refugees, asylum seekers, and potential victims deported or turned away at border points without being screened for trafficking indicators?',    'status' => 1],
            ['title' => '41.Did law enforcement officials screen for trafficking when detaining or arresting individuals in commercial sex, migrants, or other vulnerable groups?',    'status' => 1],
            ['title' => '42.What, if any, support did the government provide to victims who assisted in the investigation and prosecution of trafficking cases? Examples of support include immigration relief, legal support and advice, witness protection, victim-witness advocates, and funding for transportation and/or lodging.',    'status' => 1],
            ['title' => '43.Did the government provide a recovery and reflection period? If yes, did this period include a secure shelter option? Was it accessible to all victims, including men, boys, and underserved communities?',    'status' => 1],
            ['title' => '44.How many newly identified victims participated in the investigation and prosecution of traffickers?',    'status' => 1],
            ['title' => '45.What, if any, alternatives were victims presented with to speaking with law enforcement while participating in investigations? What steps, if any, did the authorities take to minimize the number of times a victim must be interviewed throughout the criminal justice process? Did law enforcement allow a representative or advocate to accompany victims during interviews?',    'status' => 1],
            ['title' => '46.What, if any, legal assistance did the government fund and provide to trafficking victims? What, if any, forms of legal aid did it offer to assist with cases on related legal matters, such as criminal charges, family law or protective orders, etc.?',    'status' => 1],
            ['title' => '47.What forms of victim-witness protection services did the government provide to protect participating victims’ physical security and privacy during proceedings? What, if any, accommodations did the government provide for victims with disabilities during trials?',    'status' => 1],
            ['title' => '48. Could victims provide testimony via video or written statements? How many, if any, participated via these methods?',    'status' => 1],
            ['title' => '49. Could victims obtain restitution from defendants in criminal cases? Were criminal justice officials adequately trained to seek and order restitution for victims during criminal cases and did they do so?',    'status' => 1],
            ['title' => '50. How many convicted traffickers were ordered to pay restitution to a victim and what amounts were they ordered to pay?',    'status' => 1],
            ['title' => '51.Did the government maintain a victim compensation fund?',    'status' => 1],
            ['title' => '52.Is there a designated lead anti-trafficking official, agency, and/or a national coordinating body?',    'status' => 1],
            ['title' => '53.Did the government seek civil society and/or survivors’ input in crafting or implementing any new anti-trafficking laws, regulations, policies, programs?',    'status' => 1],
            ['title' => '54.Did the government take new or ongoing steps to ensure policies did not further marginalize communities already overrepresented among trafficking victims?',    'status' => 1],
            ['title' => '55.How much funding (in the local currency) did the government spend on prevention efforts (e.g., awareness campaigns, research projects, national action plan implementation, etc.)?',    'status' => 1],
            ['title' => '56.Did the government create or update a national action plan to address trafficking? If yes, provide a copy (in English, if available).',    'status' => 1],
            ['title' => '57.What resources (funding or in-kind) did the government devote to implement new/updated or existing national action plans?',    'status' => 1],
            ['title' => '58.Did the government conduct or fund new projects to research or assess trafficking issues within the country or of its nationals abroad? Did the government publicize its efforts to combat trafficking?',    'status' => 1],
            ['title' => '59.Did the government fund and/or conduct awareness activities? Note if these activities were new or ongoing.',    'status' => 1],
            ['title' => '60.Did the government carry out any efforts to raise awareness or train foreign governments on trafficking?',    'status' => 1],
            ['title' => '61.Were awareness-raising materials readily available to intended audiences, cost-free, and accessible in various languages, including braille?',    'status' => 1],
            ['title' => '62.What strategies did awareness-raising campaigns employ to ensure messaging and images did not legitimize and/or perpetuate harmful or racialized narratives and/or stereotypes of victims/survivors and perpetrators?',    'status' => 1],
            ['title' => '63.Did the government change how it regulated and oversaw labor recruitment for licensed and unlicensed recruitment agencies, individual recruiters, and sub-brokers?',    'status' => 1],
            ['title' => '64. Did the government prohibit worker-paid recruitment fees?',    'status' => 1],
            ['title' => '65. Did the government have agreements, with a transparent oversight mechanism, with other countries on safe and responsible labor recruitment that included measures to prevent trafficking vulnerable people seeking work in those countries? Were these agreements implemented during the reporting period?',    'status' => 1],
            ['title' => '66.Did the government allow migrant workers to change employers without obtaining special permissions?',    'status' => 1],
            ['title' => '67.Did the government take tangible action to prevent forced labor in supply chains?',    'status' => 1],
            ['title' => '68.Did the government make any new efforts ensure its trade or migration policies did not facilitate trafficking?',    'status' => 1],
            ['title' => '69.Did the government make any efforts to prohibit and prevent trafficking in public procurement supply chains?',    'status' => 1],
            ['title' => '70.What measures not mentioned elsewhere did the government take to reduce the demand for commercial sex acts by targeting consumers? (NOTE: These measures should target consumers – not suppliers or facilitators – of commercial sex. Law enforcement efforts against brothels or individuals in commercial sex are not considered efforts to reduce the demand for commercial sex.)',    'status' => 1],
            ['title' => '71.In countries with legalized or decriminalized “prostitution,” describe the laws related to commercial sex, and describe any efforts to discourage the purchase of commercial sex within legal or decriminalized “prostitution” activities. Did these laws/efforts apply to all individuals in the commercial sex industry, including foreign nationals?',    'status' => 1],
            ['title' => '72.Did the government continue or make new efforts to reduce its nationals’ or foreigners’ participation in domestic and extraterritorial child sexual exploitation? Did authorities identify victims of child sex trafficking exploited by domestic or foreign tourists during the reporting period? If so, please provide details.',    'status' => 1],
            ['title' => '73.Did the government train its diplomats not to engage in or facilitate trafficking?',    'status' => 1],
            ['title' => '74.Did country diplomats allegedly exploit domestic workers overseas (e.g., worker pay is low or given in the form of food and/or accommodation)?',    'status' => 1],
            ['title' => '75.Did the government provide anti-trafficking training to its nationals deployed abroad on peacekeeping or other similar missions?',    'status' => 1],
            ['title' => '76.Describe human trafficking trends, drivers, methods, foreign victim nationalities, source/destination dynamics, sectors, affected demographics, etc. during the reporting period?',    'status' => 1],
            ['title' => '77.Which groups are at particular risk of sex trafficking?',    'status' => 1],
            ['title' => '78.Which groups are at particular risk of forced labor?',    'status' => 1],
            ['title' => '79.Climate change compounds vulnerabilities to sex trafficking and forced labor worldwide. Provide any information about trafficking trends or risk factors stemming from slow-onset climate-related change and sudden-onset climate-related disasters, as well as any efforts to mitigate these vulnerabilities.',    'status' => 1],
            ['title' => '80.Are any of the following persons present in the country as part of government-to-government agreements and/or in foreign government-affiliated projects? If present, are these individuals subjected to or at high risk of forced labor?',    'status' => 1],
            ['title' => '81.Did foreign security personnel exploit people in human trafficking crimes, including forced labor, and sex trafficking?',    'status' => 1],
            ['title' => '82.Did foreign-directed development, infrastructure, agriculture, or extractive enterprises exploit people in forced labor, sex trafficking, or use (Belt and Road Initiative, medical missions, etc.)?',    'status' => 1],
            ['title' => '83.Technology and Trafficking: If applicable, describe how traffickers use technology to recruit and exploit victims and how governments combat these forms of human trafficking.',    'status' => 1],
            ['title' => '84.Describe any online scam operations involving indicators of trafficking indicators identified during the reporting period. What are the victims’ nationalities? How did the government respond? Did governments help repatriate victims?',    'status' => 1],
            ['title' => '85.Provide information about trafficking trends and government anti-trafficking efforts in territories or semi-autonomous regions.',    'status' => 1],

        ];

        foreach ($questions as $question) {
            QuestionTitle::create([
                'title'   => $question['title'],
                'status' => $question['status'],
            ]);
        }
    }
}
